In [ ]:
#access numpy and np for convenience
import numpy as np

In [2]:
#create arrays-grid of numbers
a = np.array([1, 2, 3])

In [3]:
#multidimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
#generators- auto create arrays with specific patterns/values
np.zeros((2, 3))  
np.ones((3,))
np.arange(0,10,2)
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#inspect arrays-understand shape and structure of arrays
a.shape #3 elements in 1d rows & columns
a.ndim #1 dimension number of dimensions
a.size #total number of elements
a.dtype #data type of elements in array


In [ ]:
#1D indexing(single element) and slicing(a range)-grab parts 
a=np.array([10, 20, 30, 40, 50])
a[0]  #first element-10
a[-1] #last element-50
a[1:4] #slice from index 1 to 3 (4 is excluded)-[20,30,40]

#2D
b=np.array([[1,2,],[3,4,],[5,6,]])
b[0,1] #row 0, column 1
b[:,0] #all rows, column 0

array([20, 30, 40])

In [ ]:
#array math
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y       #[5,7,9]element-wise addition
x*y       #[4,10,18]element-wise multiplication
np.sqrt(x) #[1.0,1.414,1.732]element-wise square root
np.su(x)  #6 sum of all elements
np.mean(x) #2.0 mean of all elements

In [ ]:
#simulate returns
returns = np.random.normal(loc=0.001, scale=0.02,size=(30,5))
#np.randm.normal-generates random numbers from normal distribution
#loc-mean of distribution(0.1%)
#scale-standard deviation of distribution-volatility(2%)
#size-shape of  array(30 days, 5 assets)

np.mean(returns, axis=0) #mean return for each asset over 30 days
np.std(returns, axis=0)  #std dev for each asset over 30 days

#axis=0-calculate across rows for each column
#np.std- standard deviation

array([0.01739081, 0.01469357, 0.0252588 , 0.01947423, 0.01639828])